apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalyanamapp
spec:
  replicas: 1  # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: kalyanamapp
  template:
    metadata:
      labels:
        app: kalyanamapp
    spec:
      containers:
        - name: angular-app-container
          image: codedecode25/food-delivery-app-fe:4
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:  
  selector:
    app: kalyanamapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
